runtime: python39
entrypoint: gunicorn -b :$PORT app:app

service_account: instructiq@instructiq-456811.iam.gserviceaccount.com

env_variables:
  REDIRECT_URI: "https://instructiq-456811.appspot.com/callback"
  SESSION_TYPE: "filesystem"
  SESSION_FILE_DIR: "/tmp"

handlers:
- url: /nltk_data
  static_dir: nltk_data
- url: /static
  static_dir: static
- url: /assets
  static_dir: assets
- url: /.*
  script: auto
  secure: always

instance_class: F1